FROM blackappsolutions/alpine-docker-jdk11-maven3.6:1
# https://gitlab.com/provocon/coremedia-build-docker/blob/master/Dockerfile
ENV PATH $PATH:/usr/local/sencha

RUN \
  apk add sudo font-noto && fc-cache -fv && \
  curl http://cdn.sencha.com/cmd/6.7.0.63/no-jre/SenchaCmd-6.7.0.63-linux-amd64.sh.zip > /usr/local/sencha.zip && \
  cd /usr/local && unzip /usr/local/sencha.zip && \
  /usr/local/SenchaCmd-6.7.0.63-linux-amd64.sh -q -d --illegal-access=warn -dir /usr/local/sencha/6.7.0.63 && \
  mkdir /usr/local/sencha/repo && chmod 777 /usr/local/sencha/repo && \
  ln -s /usr/local/sencha/sencha-6.7.0.63 /usr/local/bin/sencha && \
  curl -L https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 > phantomjs.tar.bz2 && \
  tar xjf phantomjs.tar.bz2 && \
  ln -s /usr/local/phantomjs-*/bin/phantomjs /usr/local/bin/phantomjs && \
  rm -f sencha.zip phantomjs.tar.bz2 SenchaCmd-6.7.0.63-linux-amd64.sh
