#!/usr/bin/env groovy

pipeline {
  agent none
  options {
    disableConcurrentBuilds()
    buildDiscarder(logRotator(numToKeepStr: '11'))
    timestamps()
  }
  triggers {
    bitbucketPush()
    pollSCM('')
  }
  stages {
    stage('build') {
      agent {
        docker {
          image 'blackappsolutions/coremedia-build:CMCC_S-2010.2'
          args '-u root --cap-add=NET_ADMIN'
        }
      }
      steps {
        script {
          dir('.') {
            try {
              sh label: 'cmcc_build', script: '''              
              mkdir ~/.ssh
              chmod 600 workspace-configuration/id_rsa_CLIENTNAME_jenkins
              cp workspace-configuration/id_rsa_CLIENTNAME_jenkins ~/.ssh               
              cp workspace-configuration/ssh-config ~/.ssh/config
              ssh-keyscan -t rsa bastion.sandbox.CLIENTNAME.coremedia.cloud >> ~/.ssh/known_hosts
              
              sshuttle --no-latency-control -l 0.0.0.0:0 -r bastion.sandbox.CLIENTNAME.coremedia.cloud 172.16.0.0/16 --daemon
              
              STUFF_TO_SKIP="-DskipThemes=true -DskipContent=true -Dskip-joo-unit-tests=true -DskipTests -Dmdep.analyze.skip=true -Denforcer.skip=true"                                   
              mvn -s workspace-configuration/settings.xml install $STUFF_TO_SKIP                     
              '''
            } finally {
              sh label: 'reset_permissions', script: 'chmod -R 777 .'
            }
          }
        }
      }
    }
  }
  post {
    always {
      node('master') {
        notifyBitbucket commitSha1: '', considerUnstableAsSuccess: false, credentialsId: 'ci-cd-emea-bitbucket-user-id',
            disableInprogressNotification: false, ignoreUnverifiedSSLPeer: false, includeBuildNumberInKey: false,
            prependParentProjectKey: false, projectKey: '', stashServerBaseUrl: 'https://digital.CLIENTNAME.com/stash',
            buildName: BUILD_DISPLAY_NAME, buildStatus: env.BUILD_STATUS
      }
    }
  }
}
